[project]
name = "gambot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.3",
    "apscheduler<3.11",
    "beautifulsoup4>=4.14.3",
    "chinesecalendar>=1.11.0",
    "kurigram>=2.2.17",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "telethon>=1.42.0",
    "tqdm>=4.67.1",
]
